### PR TITLE
Integrate PGconverter tool and MzTabConverterTool

### PR DESCRIPTION
**Pull request by sureshhewabi**
## Summary

- I mainly integrate PGconverter tool and MzTabConverterTool so that they are runnable by a single command-line main class. 
- I changed the style of commands in MzTabConverterTool to be unified with PGconverter tool.
- Certain methods of PGconverter were moved into new classes to modularise the code
- I added new unit test to check the integration works fine

### CODE REVIEW

**Comment by Tobias-Ternent** [comment]
Should the AssayFileSummary class be renamed to ResultFileSummary ?

**Comment by ypriverol** [comment]
Agre with @Tobias-Ternent as we discuss before we should remove the term assay from pride to name ResultFiles

**Comment by sureshhewabi** [comment]
Yes, I have already renamed AssayFileSummary to ResultFileSummary.

**Comment by Tobias-Ternent** [comment]
I need to spend some extra time looking at why the unit tests are "stopping" early, will have to be early next week.

**Pull request merged**
